version: '3.4'

services: 
  postgres:
    container_name: pg_gostack
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "db_go_stack"
      POSTGRES_USER: "jeanfernandes"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - "./volumes/postgres"

  mongodb:
    container_name: mongo_gostack
    image: mongo:3.6
    ports:
    - "27017:27017"
    volumes:
    - ./volumes/mongodb

  redis:
    container_name: redis_gostack
    image: redis:alpine
    ports:
    - "6379:6379"
    volumes:
    - /volumes/redis:/data

  api:
    container_name: backend_gostack
    depends_on:
      - postgres
      - redis
      - mongodb
    build: .
    ports: 
    - "8080:8080"